export { default as Home } from './Home/index'
export { default as Login } from './Login/index'
export { default as Panel } from './Panel/index'
export { default as TaskAdd } from './TaskAdd/index'
export { default as TaskEdit } from './TaskEdit/index'
export { default as NotFound } from './NotFound/index'